version: 2
updates:
  # Monitoramento de dependências do Frontend (Node / npm)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
      - "frontend"

  # Monitoramento de dependências do Backend (Node / npm)
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
      - "backend"

  # Monitoramento de dependências do Backend (Python / pip) caso seja adotado
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
      - "backend"

  # Monitoramento de segurança dos próprios Workflows do GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "ci/cd"
      - "security"
