export const MATERNO_INDICATORS = [
  {
    id: "pn1",
    name: "Início do pré-natal no 1º trimestre",
    value: "78,4%",
    unit: "%",
    parameter: "≥ 70%",
    status: "ok",
    trend: "↑ +3,2pp",
    period: "Jan/2025",
    source: "e-SUS / PEC",
    formula: "Gestantes c/ 1ª consulta até 12ª semana / Total gestantes × 100",
    definition: "Proporção de gestantes que iniciaram o pré-natal até o 1º trimestre de gestação.",
    frequency: "Mensal",
    limitations: "Subnotificação em partos domiciliares. Atraso de até 30 dias na consolidação PEC.",
    line: "Materno-Infantil",
  },
  {
    id: "pn2",
    name: "Média de consultas pré-natal",
    value: "5,2",
    unit: "consultas",
    parameter: "≥ 6",
    status: "alert",
    trend: "↔ -0,1",
    period: "Jan/2025",
    source: "e-SUS / PEC",
    formula: "Total de consultas pré-natal / Total de partos no período",
    definition: "Número médio de consultas pré-natal realizadas por gestante.",
    frequency: "Mensal",
    limitations: "Não inclui consultas em serviços privados sem convênio SUS.",
    line: "Materno-Infantil",
  },
  {
    id: "vac1",
    name: "Cobertura vacinal infantil (DPT)",
    value: "91,2%",
    unit: "%",
    parameter: "≥ 95%",
    status: "alert",
    trend: "↓ -1,8pp",
    period: "Dez/2024",
    source: "SI-PNI / SIPNI",
    formula: "Crianças c/ esquema DPT até 15 meses / Pop. estimada × 100",
    definition: "Cobertura vacinal para tríplice bacteriana (DPT) em crianças até 15 meses.",
    frequency: "Quadrimestral",
    limitations: "Pop. estimada pode divergir do Censo. Registro tardio em UBS remotas.",
    line: "Materno-Infantil",
  },
  {
    id: "mort1",
    name: "Taxa de mortalidade infantil",
    value: "8,3",
    unit: "por 1.000 NV",
    parameter: "< 10",
    status: "ok",
    trend: "↑ -0,7",
    period: "2024",
    source: "SIM / SINASC",
    formula: "Óbitos < 1 ano / Nascidos vivos × 1.000",
    definition: "Número de óbitos de menores de 1 ano por mil nascidos vivos.",
    frequency: "Anual",
    limitations: "Dado anual — disponível com atraso de 6-12 meses.",
    line: "Materno-Infantil",
  },
  {
    id: "sif1",
    name: "Sífilis congênita (taxa)",
    value: "4,1",
    unit: "por 1.000 NV",
    parameter: "< 0,5",
    status: "worsening",
    trend: "↓ +0,6",
    period: "Dez/2024",
    source: "SINAN",
    formula: "Casos sífilis congênita / Nascidos vivos × 1.000",
    definition: "Taxa de incidência de sífilis congênita por mil nascidos vivos.",
    frequency: "Mensal",
    limitations: "Subnotificação estimada de 30-40% nas bases regionais.",
    line: "Materno-Infantil",
  },
  {
    id: "aleit",
    name: "Aleitamento materno exclusivo (6 meses)",
    value: "43,7%",
    unit: "%",
    parameter: "≥ 50%",
    status: "alert",
    trend: "↑ +2,1pp",
    period: "Dez/2024",
    source: "e-SUS / PEC",
    formula: "Crianças c/ AME até 6 meses / Total crianças 6 meses × 100",
    definition: "Proporção de crianças que receberam aleitamento materno exclusivo até os 6 meses.",
    frequency: "Semestral",
    limitations: "Dado sujeito a recordação materna — possível viés.",
    line: "Materno-Infantil",
  },
];

export const CANCER_INDICATORS = [
  {
    id: "fit1",
    name: "Realização do FIT (rastreamento)",
    value: "34,7%",
    unit: "%",
    parameter: "≥ 60%",
    status: "alert",
    trend: "↑ +5,1pp",
    period: "Jan/2025",
    source: "e-SUS / PEC",
    formula: "Pessoas 45-75a c/ FIT / Pop. elegível 45-75a × 100",
    definition: "Proporção da população elegível que realizou o teste FIT.",
    frequency: "Quadrimestral",
    limitations: "Elegibilidade estimada por faixa etária cadastrada.",
    line: "Câncer Colorretal",
  },
  {
    id: "col1",
    name: "Colonoscopia após FIT positivo",
    value: "61,5%",
    unit: "%",
    parameter: "≥ 80%",
    status: "alert",
    trend: "↑ +8,3pp",
    period: "Dez/2024",
    source: "Complexo São João de Deus",
    formula: "Colonoscopias realizadas / FIT positivos encaminhados × 100",
    definition: "Proporção de pacientes com FIT positivo que realizaram colonoscopia.",
    frequency: "Quadrimestral",
    limitations: "Depende de integração com sistemas hospitalares — atraso médio de 45 dias.",
    line: "Câncer Colorretal",
  },
  {
    id: "trat1",
    name: "Início do tratamento em até 60 dias",
    value: "72,3%",
    unit: "%",
    parameter: "≥ 80%",
    status: "alert",
    trend: "↑ +4,1pp",
    period: "Dez/2024",
    source: "SIH/SUS + Hospital",
    formula: "Casos c/ início ≤ 60 dias / Total casos × 100",
    definition: "Proporção de pacientes que iniciaram tratamento em até 60 dias.",
    frequency: "Semestral",
    limitations: "Data de diagnóstico pode estar ausente em alguns registros.",
    line: "Câncer Colorretal",
  },
  {
    id: "sobr",
    name: "Sobrevida em 3 anos",
    value: "67,2%",
    unit: "%",
    parameter: "≥ 70%",
    status: "alert",
    trend: "↑ +1,4pp",
    period: "2022-2024",
    source: "SIH/SUS + RHC",
    formula: "Casos vivos 3 anos após diagnóstico / Total casos diagnosticados × 100",
    definition: "Proporção de pacientes vivos 3 anos após diagnóstico de câncer colorretal.",
    frequency: "Anual",
    limitations: "Requer linkage entre bases — perda de seguimento estimada em 12%.",
    line: "Câncer Colorretal",
  },
  {
    id: "enc1",
    name: "Encaminhamento para investigação (FIT+)",
    value: "88,4%",
    unit: "%",
    parameter: "≥ 90%",
    status: "ok",
    trend: "↑ +2,7pp",
    period: "Jan/2025",
    source: "e-SUS / PEC",
    formula: "FIT positivos encaminhados / Total FIT positivos × 100",
    definition: "Proporção de pacientes com FIT positivo encaminhados para investigação especializada.",
    frequency: "Mensal",
    limitations: "Encaminhamentos informais podem não ser registrados.",
    line: "Câncer Colorretal",
  },
];

export const NAVEGACAO_INDICATORS = [
  {
    id: "nav1",
    name: "Taxa de referência com retorno",
    value: "64,3%",
    unit: "%",
    parameter: "≥ 75%",
    status: "alert",
    trend: "↑ +4,2pp",
    period: "Jan/2025",
    source: "e-SUS / PEC + SISREG",
    formula: "Referências com contrarreferência / Total de referências × 100",
    definition: "Proporção de encaminhamentos para especialidade que retornaram contrarreferência à UBS.",
    frequency: "Mensal",
    limitations: "Sistemas de referência e contrarreferência têm integração parcial.",
    line: "Navegação do Cuidado",
  },
  {
    id: "nav2",
    name: "Tempo médio de espera para especialidade",
    value: "47",
    unit: "dias",
    parameter: "≤ 30 dias",
    status: "worsening",
    trend: "↓ +3 dias",
    period: "Jan/2025",
    source: "SISREG",
    formula: "Soma dos tempos de espera / Total de consultas especializadas realizadas",
    definition: "Tempo médio entre o encaminhamento e a realização da consulta especializada.",
    frequency: "Mensal",
    limitations: "Considera apenas especialidades reguladas via SISREG.",
    line: "Navegação do Cuidado",
  },
  {
    id: "nav3",
    name: "Resolubilidade na atenção primária",
    value: "82,1%",
    unit: "%",
    parameter: "≥ 85%",
    status: "stable",
    trend: "↔ 0,0pp",
    period: "Jan/2025",
    source: "e-SUS / PEC",
    formula: "Atendimentos resolvidos na APS / Total de atendimentos × 100",
    definition: "Proporção de atendimentos resolvidos sem necessidade de encaminhamento.",
    frequency: "Mensal",
    limitations: "Definição de 'resolvido' ainda em validação com equipes.",
    line: "Navegação do Cuidado",
  },
  {
    id: "nav4",
    name: "Cobertura de equipes de SF",
    value: "78,6%",
    unit: "%",
    parameter: "≥ 80%",
    status: "stable",
    trend: "↑ +0,4pp",
    period: "Jan/2025",
    source: "e-GESTOR / SIAPS",
    formula: "Pop. coberta por equipes SF / Pop. total × 100",
    definition: "Proporção da população coberta por equipes de Saúde da Família.",
    frequency: "Quadrimestral",
    limitations: "Cobertura estimada com base no cadastro de famílias.",
    line: "Navegação do Cuidado",
  },
  {
    id: "nav5",
    name: "Abandono de tratamento (crônicas)",
    value: "18,4%",
    unit: "%",
    parameter: "≤ 10%",
    status: "worsening",
    trend: "↓ +2,1pp",
    period: "Dez/2024",
    source: "e-SUS / PEC",
    formula: "Pacientes c/ +90 dias sem registro / Total pacientes ativos × 100",
    definition: "Proporção de pacientes com doenças crônicas sem atendimento há mais de 90 dias.",
    frequency: "Quadrimestral",
    limitations: "Considera apenas pacientes com registro ativo no e-SUS.",
    line: "Navegação do Cuidado",
  },
];

export const CONEXAO_INDICATORS = [
  {
    id: "con1",
    name: "Cobertura do Programa Bolsa Família (saúde)",
    value: "89,3%",
    unit: "%",
    parameter: "≥ 90%",
    status: "stable",
    trend: "↑ +0,8pp",
    period: "Jan/2025",
    source: "SISVAN / CadÚnico",
    formula: "Beneficiários c/ condicionalidades de saúde cumpridas / Total beneficiários × 100",
    definition: "Proporção de beneficiários do Bolsa Família com condicionalidades de saúde em dia.",
    frequency: "Semestral",
    limitations: "Integração CadÚnico–SISVAN pode ter defasagem de até 2 meses.",
    line: "Conexão Colaborativa",
  },
  {
    id: "con2",
    name: "Adesão ao rastreamento (Bolsa Família)",
    value: "41,2%",
    unit: "%",
    parameter: "≥ 50%",
    status: "alert",
    trend: "↑ +6,3pp",
    period: "Dez/2024",
    source: "e-SUS / PEC + CadÚnico",
    formula: "Beneficiários PBF rastreados / Total elegíveis PBF × 100",
    definition: "Proporção de beneficiários do PBF elegíveis que realizaram rastreamento preventivo.",
    frequency: "Quadrimestral",
    limitations: "Elegibilidade baseada em critérios de faixa etária — não inclui critérios clínicos individuais.",
    line: "Conexão Colaborativa",
  },
  {
    id: "con3",
    name: "Vulnerabilidade social em risco nutricional",
    value: "14,7%",
    unit: "%",
    parameter: "< 10%",
    status: "worsening",
    trend: "↓ +1,9pp",
    period: "Dez/2024",
    source: "SISVAN",
    formula: "Crianças < 5a em risco nutricional / Total crianças < 5a acompanhadas × 100",
    definition: "Proporção de crianças menores de 5 anos em risco nutricional acompanhadas pelo SISVAN.",
    frequency: "Quadrimestral",
    limitations: "Cobertura do SISVAN estimada em 60% das crianças elegíveis.",
    line: "Conexão Colaborativa",
  },
];

export const ALL_INDICATORS = [
  ...MATERNO_INDICATORS,
  ...CANCER_INDICATORS,
  ...NAVEGACAO_INDICATORS,
  ...CONEXAO_INDICATORS,
];

export const CARD_TO_PAGE = {
  materno: "Materno-Infantil",
  cancer: "Câncer Colorretal",
  navegacao: "Navegação do Cuidado",
  conexao: "Conexão Colaborativa",
  ods: "ODS",
};
